name: Security Check Bandit

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install python3 python3-pip -y
        pip install bandit

    - name: Run pylint
      run: |
        bandit *.py